language: php

php:
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist $PREFER_LOWEST

script:
    - composer validate --strict

    - vendor/bin/ecs check tests
