language: php

php:
    - 7.3
    - 7.4
    - 8.0

env:
    - ECS_VERSION="^9.0"

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist $COMPOSER_FLAGS

script:
    - composer validate --strict

    - vendor/bin/ecs check --config ecs.php tests ecs.php
